Repository ucsb-cs156-w24/proj-happy-cows-w24-4pm-2, pull requests merged in 2024-03, with the labels that each got.

#17 added entity and repository for AnnouncementTable
  src/main/java/edu/ucsb/cs156/happiercows/entities/Announcement.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/AnnouncementRepository.java
Labels: 5

#18 Added showChat boolean to Commons entity
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
Labels: 5

#31 AS - disallowed buying negative cows + tests
  frontend/src/main/components/Commons/ManageCowsModal.js
  frontend/src/tests/components/Commons/ManageCowsModal.test.js
Labels: 10

#33 Angelina selling negative cows
  frontend/src/main/components/Commons/ManageCowsModal.js
  frontend/src/tests/components/Commons/ManageCowsModal.test.js
Labels: 10

#19 Fixed usage of class -> className
  frontend/src/main/pages/HomePage.js
Labels: 5

#34 Enabled admins to set showChat in API
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: 10

#39 Bharat UX Improvements to Leaderboard page
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/tests/pages/LeaderboardPage.test.js
Labels: 5

#30 Rohan Issue F1 + B2: Frontend for AnnouncementForm/Table and Backend CRUD Operations for Announcement Endpoints
  frontend/src/fixtures/announcementFixtures.js
  frontend/src/main/components/Announcement/AnnouncementForm.js
  frontend/src/main/components/Announcement/AnnouncementTable.js
  frontend/src/main/utils/announcementUtils.js
  frontend/src/stories/components/Announcement/AnnouncementForm.stories.js
  frontend/src/stories/components/Announcement/AnnouncementTable.stories.js
  frontend/src/tests/components/Announcement/AnnouncementsForm.test.js
  frontend/src/tests/components/Announcement/AnnouncementsTable.test.js
  frontend/src/tests/utils/announcementUtils.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Announcement.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/AnnouncementRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsControllerTests.java
Labels: 20

#35 Add show chat to commons table
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/fixtures/reportFixtures.js
  frontend/src/fixtures/reportLineFixtures.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
Labels: 10

#36 Add show chat checkbox to commons form
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
Labels: 10
